[package]
name = "ug-scraper"
version = "0.1.0"
edition = "2021"
license-file = "LICENCE"
description = "An API to get data from Ultimate Guitar using web-scraping"
repository = "https://github.com/Lich-Corals/ug-scraper-rs"
readme = "README.md"
keywords = ["ultimate-guitar", "music", "web-scraping", "guitar", "api"]
authors = ["Linus Tibert"]

exclude = [
    ".github",
    ".gitignore",
]

[dependencies]
html-escape = "0.2.13"
percent-encoding = "2.3.1"
regex = "1.11.1"
ureq = "3.0.12"
