[package]
name = "ug-scraper"
version = "0.2.7"
edition = "2021"
license = "MIT"
description = "An API to get data from Ultimate Guitar using web-scraping"
repository = "https://codeberg.org/Lich-Corals/ug-scraper-rs"
documentation = "https://docs.rs/ug-scraper/"
readme = "README.md"
keywords = ["ultimate-guitar", "music", "web-scraping", "guitar", "api"]

exclude = [
    ".github",
    ".gitignore",
]

[dependencies]
html-escape = "0.2.13"
percent-encoding = "2.3.2"
regex = "1.11.3"
ureq = "3.1.2"

[dependencies.serde]
version = "1.0.228"
features = ["derive"]
