name: Current test status

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches: [ "mistress" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Notify on Failure
      if: failure()
      uses: fjogeleit/http-request-action@v1      
      with:
        url: 'https://api.telegram.org/bot${{ secrets.API_KEY }}/sendMessage?chat_id=${{ secrets.CHAT_ID }}&text=${{ secrets.MESSAGE }}'
      
